language: go
go_import_path: github.com/ReconfigureIO/web-md5

go:
  - 1.9

install:
- wget "https://github.com/Masterminds/glide/releases/download/v0.13.1/glide-v0.13.1-linux-amd64.tar.gz"
- tar -vxz -C /usr/local/bin --strip=1 -f glide-0.10.2-linux-amd64.tar.gz

- curl -LO https://s3.amazonaws.com/reconfigure.io/reco/releases/reco-v0.2.0-x86_64-linux.zip
- unzip reco-v0.2.0-x86_64-linux.zip
- sudo mv reco /usr/local/bin
- reco version

- glide install

script:
  - make test
